
package jswing.Login;

import jswing.Button;
import jswing.Password;
import jswing.TextField;

public class Login extends javax.swing.JFrame {

        public Login() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jCheckBox1 = new javax.swing.JCheckBox();
                textField2 = new TextField();
                password1 = new Password();
                button1 = new Button();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel2.setBackground(new java.awt.Color(76, 76, 76));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Log in to your Workspace");

                jLabel2.setIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\icons8-user-64.png")); // NOI18N

                jLabel3.setIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\icons8-padlock-64.png")); // NOI18N

                jButton1.setBackground(new java.awt.Color(76, 76, 76));
                jButton1.setForeground(new java.awt.Color(76, 76, 76));
                jButton1.setIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\a09eb-8nsbj-001.png")); // NOI18N
                jButton1.setBorder(null);
                jButton1.setContentAreaFilled(false);
                jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jButton2.setBackground(new java.awt.Color(76, 76, 76));
                jButton2.setForeground(new java.awt.Color(76, 76, 76));
                jButton2.setIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\a26mm-y5gra-001.png")); // NOI18N
                jButton2.setBorder(null);
                jButton2.setContentAreaFilled(false);
                jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jButton3.setBackground(new java.awt.Color(76, 76, 76));
                jButton3.setForeground(new java.awt.Color(76, 76, 76));
                jButton3.setIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\aahm6-0kfcy-001.png")); // NOI18N
                jButton3.setBorder(null);
                jButton3.setContentAreaFilled(false);
                jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jCheckBox1.setToolTipText("Show Password");
                jCheckBox1.setDisabledIcon(null);
                jCheckBox1.setIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\anz6u-19e8e-001.png")); // NOI18N
                jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\a5e4g-5jzpu-001.png")); // NOI18N

                textField2.setForeground(new java.awt.Color(255, 255, 255));
                textField2.setText("Username or Email");

                password1.setForeground(new java.awt.Color(255, 255, 255));
                password1.setText("password1");

                button1.setBackground(new java.awt.Color(51, 153, 255));
                button1.setForeground(new java.awt.Color(255, 255, 255));
                button1.setText("Sign In");
                button1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                jLabel4.setIcon(new javax.swing.ImageIcon(
                                "C:\\Users\\Admin\\OneDrive\\SJSU M.S. Data Science Road Map\\SJSU\\CS 151 - Object Oriented Design\\CS151-TaskManagement\\app\\TaskManagement\\src\\icons\\icons8-tree-structure-64.png")); // NOI18N

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Radix");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Forgot Password?");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(78, 78, 78)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(80, 80, 80)
                                                                                                .addComponent(jLabel4)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel5))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel2))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel1)
                                                                                                                                                .addComponent(textField2,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                266,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGap(35, 35, 35))
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(38, 38, 38)
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(button1,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                175,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(jButton1)
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addComponent(jButton2)
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addComponent(jButton3))))
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(password1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                266,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jCheckBox1))))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(148, 148, 148)
                                                                                                .addComponent(jLabel6)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                121,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(143, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(61, 61, 61)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel5))
                                                                .addGap(39, 39, 39)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(12, 12, 12)
                                                                                                .addComponent(textField2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                44,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jCheckBox1)
                                                                                .addComponent(password1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                44,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(button1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel6)
                                                                .addGap(23, 23, 23)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jButton2)
                                                                                .addComponent(jButton1)
                                                                                .addComponent(jButton3))
                                                                .addGap(350, 350, 350)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 673, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Login().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private Button button1;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private Password password1;
        private TextField textField2;
        // End of variables declaration
}
