package jswing;

import jswing.model.ModelTaskTableAction;
import javax.swing.Icon;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class TableTaskIcons extends javax.swing.JPanel {

    public TableTaskIcons(ModelTaskTableAction data) {
        initComponents();
        addImage();
        editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                data.getEvent().update(data.getTask());
            }
        });
        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                data.getEvent().delete(data.getTask());
            }
        });
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        grphcs.setColor(new Color(230, 230, 230));
        grphcs.drawLine(0, getHeight() - 1, getWidth(), getHeight() - 1);
    }

    private void addImage() {
        Icon edit = IconFontSwing.buildIcon(GoogleMaterialDesignIcons.EDIT, 20, new Color(255, 255, 255));
        Icon delete = IconFontSwing.buildIcon(GoogleMaterialDesignIcons.DELETE, 20, new Color(255, 255, 255));
        editButton.setIcon(edit);
        deleteButton.setIcon(delete);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        editButton = new ButtonEffect();
        deleteButton = new ButtonEffect();

        editButton.setBackground(new java.awt.Color(0, 153, 255));
        // editButton.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-20.png")));
        editButton.setMaximumSize(new java.awt.Dimension(28, 28));

        deleteButton.setBackground(new java.awt.Color(255, 51, 51));
        // deleteButton.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-20.png")));
        deleteButton.setPreferredSize(new java.awt.Dimension(28, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
    }// </editor-fold>

    // Variables declaration - do not modify
    private ButtonEffect deleteButton;
    private ButtonEffect editButton;
    // End of variables declaration
}
