package jswing.component;

import jswing.ButtonEffect;
import jswing.TableDark;

import java.util.Vector;

public class DarkTableComponent extends javax.swing.JPanel {

        /**
         * Creates new form DarkTableComponent
         */
        public DarkTableComponent() {
                initComponents();
                tableDark1.fixTable(jScrollPane1);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                tableDark1 = new TableDark();
                buttonEffect2 = new ButtonEffect();
                buttonEffect3 = new ButtonEffect();
                buttonEffect4 = new ButtonEffect();

                setBackground(new java.awt.Color(51, 51, 51));

                tableDark1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                tableDark1.setColumnSelectionAllowed(true);
                jScrollPane1.setViewportView(tableDark1);
                tableDark1.getColumnModel().getSelectionModel()
                                .setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

                buttonEffect2.setBackground(new java.awt.Color(51, 153, 255));
                buttonEffect2.setForeground(new java.awt.Color(255, 255, 255));
                buttonEffect2.setText("Add Row");
                buttonEffect2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonEffect2ActionPerformed(evt);
                        }
                });

                buttonEffect3.setBackground(new java.awt.Color(0, 153, 255));
                buttonEffect3.setForeground(new java.awt.Color(255, 255, 255));
                buttonEffect3.setText("Delete Row");
                buttonEffect3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonEffect3ActionPerformed(evt);
                        }
                });

                buttonEffect4.setBackground(new java.awt.Color(0, 153, 255));
                buttonEffect4.setForeground(new java.awt.Color(255, 255, 255));
                buttonEffect4.setText("Delete Column");
                buttonEffect4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonEffect4ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502,
                                                                Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonEffect2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                78,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(buttonEffect3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonEffect4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(44, 44, 44)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(buttonEffect2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(buttonEffect3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(buttonEffect4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                422, Short.MAX_VALUE)));
        }// </editor-fold>

        private void buttonEffect2ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                Vector row = new Vector();
                int columnCount = tableDark1.getColumnCount();
                for (int i = 0; i < columnCount; i++) {
                        row.add("");
                }
                tableDark1.addRow(row);
        }

        private void buttonEffect3ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                tableDark1.deleteRow();
        }

        private void buttonEffect4ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        // Variables declaration - do not modify
        private ButtonEffect buttonEffect2;
        private ButtonEffect buttonEffect3;
        private ButtonEffect buttonEffect4;
        private javax.swing.JScrollPane jScrollPane1;
        private TableDark tableDark1;
        // End of variables declaration
}
