package jswing.form;

import serverside.Task;
import serverside.User;
import jswing.event.EventTaskComplete;
import jswing.TextField;
import jswing.Button;

import java.awt.Color;
import java.util.regex.*;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class CreateTaskForm extends javax.swing.JPanel {

    private Task task;
    private User user;
    private EventTaskComplete taskEvent;

    public CreateTaskForm() {
        initComponents();
        task = new Task();
    }

    public void setTask(Task newTask) {
        this.task = newTask;
    }

    public Task getTask() {
        return this.task;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void setTaskComplete(EventTaskComplete taskEvent) {
        this.taskEvent = taskEvent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        dateChooser2 = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        descriptionField = new TextField();
        assigneeField = new TextField();
        startDateField = new TextField();
        endDateField = new TextField();
        jLabel8 = new javax.swing.JLabel();
        priorityField = new javax.swing.JComboBox<>();
        statusField = new javax.swing.JComboBox<>();
        estimatedHoursField = new TextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        taskNameField = new TextField();
        buttonCreate = new Button();
        warningText = new javax.swing.JLabel();

        dateChooser1.setForeground(new java.awt.Color(153, 153, 255));
        dateChooser1.setTextRefernce(startDateField);

        dateChooser2.setForeground(new java.awt.Color(51, 51, 255));
        dateChooser2.setTextRefernce(endDateField);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(83, 104, 114));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Task");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Task Name*");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description*");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Assignee");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Priority*");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status*");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Start Date*");

        descriptionField.setForeground(new java.awt.Color(255, 255, 255));
        descriptionField.setText("Description");
        descriptionField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descriptionFieldKeyPressed(evt);
            }
        });

        assigneeField.setForeground(new java.awt.Color(255, 255, 255));

        startDateField.setForeground(new java.awt.Color(255, 255, 255));

        endDateField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("End Date*");

        priorityField.setBackground(new java.awt.Color(83, 104, 114));
        priorityField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priorityField.setForeground(new java.awt.Color(255, 255, 255));
        priorityField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        statusField.setBackground(new java.awt.Color(83, 104, 114));
        statusField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusField.setForeground(new java.awt.Color(255, 255, 255));
        statusField.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Not Yet Started", "On Hold", "In Progress", "Complete" }));

        estimatedHoursField.setForeground(new java.awt.Color(255, 255, 255));
        estimatedHoursField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                estimatedHoursFieldKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estimated Hours");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Optional");

        taskNameField.setForeground(new java.awt.Color(255, 255, 255));
        taskNameField.setText("Task Name");
        taskNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taskNameFieldKeyPressed(evt);
            }
        });

        buttonCreate.setBackground(new java.awt.Color(0, 153, 255));
        buttonCreate.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreate.setText("Create Task");
        buttonCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCreateMouseClicked(evt);
            }
        });

        warningText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        warningText.setForeground(new java.awt.Color(255, 255, 255));
        warningText.setText("(*) Required Fields");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel6)
                                                                                        .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel3)
                                                                                                .addComponent(jLabel2))
                                                                                        .addComponent(jLabel7)
                                                                                        .addComponent(jLabel8))
                                                                                .addGap(41, 41, 41)
                                                                                .addComponent(statusField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        230,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                466,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addComponent(jLabel9)
                                                                .addGap(27, 27, 27)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(endDateField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                230,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(startDateField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                230,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(warningText)
                                                                        .addComponent(priorityField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                230,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(descriptionField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                230,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(taskNameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                230,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel4)
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(estimatedHoursField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 230,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(assigneeField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 230,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(178, 178, 178)
                                                .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(223, 223, 223)
                                                .addComponent(jLabel10)))
                                .addContainerGap(43, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(priorityField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19,
                                        Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(estimatedHoursField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(assigneeField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(warningText)
                                .addContainerGap(87, Short.MAX_VALUE)));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>

    private void buttonCreateMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (taskNameField.getText().isEmpty() || descriptionField.getText().isEmpty()
                || startDateField.getText().isEmpty() || endDateField.getText().isEmpty()) {
            warningText.setForeground(Color.red);
            warningText.setText("Please fill in the required fields (*)");
        } else {
            String task = taskNameField.getText();
            String description = descriptionField.getText();
            String startDate = startDateField.getText();
            String endDate = endDateField.getText();
            String priority = priorityField.getSelectedItem().toString();
            String status = statusField.getSelectedItem().toString();
            String estimatedHours = estimatedHoursField.getText();
            String assignee = assigneeField.getText();
            Task newTask = new Task(task, description, status, priority, startDate, endDate, assignee, estimatedHours);
            setTask(newTask);
            this.user.createTask(getTask());
            taskEvent.taskCreated();
        }
    }

    private void estimatedHoursFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if (!onlyDigits(estimatedHoursField.getText())) {
            buttonCreate.setBackground(Color.GRAY);
            buttonCreate.setEnabled(false);
            warningText.setForeground(Color.red);
            warningText.setText("Use only digits for hours");
        } else {
            buttonCreate.setBackground(new Color(0, 153, 255));
            buttonCreate.setEnabled(true);
            warningText.setForeground(Color.WHITE);
            warningText.setText("");

        }
    }

    private void taskNameFieldKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        setButtonEnabled();
    }

    private void descriptionFieldKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        setButtonEnabled();
    }

    public boolean onlyDigits(String hours) {
        String regex = "[0-9]+";
        // Compile the ReGex
        Pattern p = Pattern.compile(regex);
        // If the string is empty
        // return false
        if (hours == null || hours.isEmpty()) {
            return true;
        }
        // Find match between given string
        // and regular expression
        // using Pattern.matcher()
        Matcher m = p.matcher(hours);
        // Return if the string
        // matched the ReGex
        return m.matches();
    }

    public void setButtonEnabled() {
        buttonCreate.setBackground(new Color(0, 153, 255));
        buttonCreate.setEnabled(true);
        warningText.setForeground(Color.WHITE);
        warningText.setText("");
    }

    // Variables declaration - do not modify
    private TextField assigneeField;
    private Button buttonCreate;
    private com.raven.datechooser.DateChooser dateChooser1;
    private com.raven.datechooser.DateChooser dateChooser2;
    private TextField descriptionField;
    private TextField endDateField;
    private TextField estimatedHoursField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> priorityField;
    private TextField startDateField;
    private javax.swing.JComboBox<String> statusField;
    private TextField taskNameField;
    private javax.swing.JLabel warningText;
    // End of variables declaration
}
