package jswing.form;

import serverside.User;
import serverside.Task;
import jswing.model.ModelTask;

import jswing.event.EventTaskComplete;
import jswing.event.EventTaskTableActions;
import jswing.TableDark;
import jswing.ImagePanel;
import jswing.ButtonEffect;

import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

public class TaskForm extends javax.swing.JPanel {
        private User user;
        private Task task;
        private CreateTaskFrame taskFrame;
        private TaskObjectFrame taskObjFrame;

        public TaskForm(User user) {
                this.user = user;
                initComponents();
                taskFrame = new CreateTaskFrame();
                taskObjFrame = new TaskObjectFrame();
                tableDark.fixTable(jScrollPane);
                initData();
                EventTaskComplete taskEvent = new EventTaskComplete() {
                        @Override
                        public void taskCreated() {
                                taskFrame.dispose();
                                revalidate();
                                repaint();
                        }

                        @Override
                        public void taskDelete() {
                                taskObjFrame.dispose();
                                revalidate();
                                repaint();

                        }

                        @Override
                        public void taskUpdate() {
                                taskObjFrame.dispose();
                                revalidate();
                                repaint();
                        }
                };
                taskFrame.setTaskEvent(taskEvent);
                taskObjFrame.setTaskEvent(taskEvent);
        }

        public void setUser(User user) {
                this.user = user;
        }

        public User getUser() {
                return this.user;
        }

        private void initData() {
                initTableData();
        }

        private void initTableData() {
                EventTaskTableActions eventAction = new EventTaskTableActions() {
                        @Override
                        public void delete(ModelTask task) {

                        }

                        @Override
                        public void update(ModelTask task) {
                                taskObjFrame.setVisible(true);
                                System.out.println("Say something stupid");

                        }
                };
                try {
                        for (int i = 0; i < this.user.getTasks().size(); i++) {
                                task = this.user.getTasks().get(i);
                                tableDark.addRow(new ModelTask(task.getTaskId(), task.getTaskName(),
                                                task.getDescription(), task.getStartDate(), task.getEndDate(),
                                                task.getPriority(), task.getStatus(), task.getNotes(),
                                                task.getAssignee()).toRowTable(eventAction));
                        }
                } catch (NullPointerException e) {
                        System.err.print("You currently have no tasks");
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jScrollPane = new javax.swing.JScrollPane();
                tableDark = new TableDark();
                imagePanel1 = new ImagePanel();
                buttonEffect1 = new ButtonEffect();

                setOpaque(false);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Tasks");

                tableDark.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "Task ID", "Task Name", "Description", "Start Date", "End Date",
                                                "Priority", "Status", "Notes", "Assigned To", "Action"
                                }));
                jScrollPane.setViewportView(tableDark);

                buttonEffect1.setForeground(new java.awt.Color(255, 255, 255));
                buttonEffect1.setText("Add Task");
                buttonEffect1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                buttonEffect1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonEffect1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
                imagePanel1.setLayout(imagePanel1Layout);
                imagePanel1Layout.setHorizontalGroup(
                                imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(imagePanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(buttonEffect1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                imagePanel1Layout.setVerticalGroup(
                                imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(11, Short.MAX_VALUE)
                                                                .addComponent(buttonEffect1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addComponent(jScrollPane,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                881, Short.MAX_VALUE)
                                                                                .addComponent(imagePanel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(24, 24, 24)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel1)
                                                                .addGap(9, 9, 9)
                                                                .addComponent(imagePanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(7, 7, 7)
                                                                .addComponent(jScrollPane)
                                                                .addGap(15, 15, 15)));
        }// </editor-fold>

        private void buttonEffect1ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                taskFrame.setVisible(true);
                taskFrame.setUser(this.user);
                taskFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

        // Variables declaration - do not modify
        private ButtonEffect buttonEffect1;
        private ImagePanel imagePanel1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane;
        private TableDark tableDark;
        // End of variables declaration
}
