package jswing.form;

import java.util.Vector;
import serverside.User;
import serverside.Task;
// import jswing.model.ModelTask;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import jswing.form.CreateTaskFrame;
import jswing.TableDark;
import jswing.ButtonEffect;

public class TaskForm extends javax.swing.JPanel {
        private User user;
        private Task task;
        private Vector row;
        private CreateTaskFrame taskFrame;

        // public TaskForm() {
        // initComponents();
        // taskFrame = new CreateTaskFrame();
        // tableDark1.fixTable(jScrollPane2);
        // initData();
        // }

        public TaskForm(User user) {
                this.user = user;
                initComponents();
                taskFrame = new CreateTaskFrame();
                tableDark1.fixTable(jScrollPane2);
                initData();
        }

        public void setUser(User user) {
                this.user = user;
        }

        public User getUser() {
                return this.user;
        }

        private void initData() {
                initTableData();
        }

        private void initTableData() {
                if (!this.user.getTasks().isEmpty()) {
                        for (int i = 0; i < this.user.getTasks().size(); i++) {
                                row = new Vector();
                                task = this.user.getTasks().get(i);
                                row.add(task.getTaskName());
                                row.add(task.getDescription());
                                row.add(task.getStartDate());
                                row.add(task.getEndDate());
                                row.add(task.getPriority());
                                row.add(task.getStatus());
                                row.add(task.getAssignee());
                                row.add(task.getEstimatedHours());
                                tableDark1.addRow(row);
                        }
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                buttonEffect1 = new ButtonEffect();
                buttonEffect2 = new ButtonEffect();
                jScrollPane2 = new javax.swing.JScrollPane();
                tableDark1 = new TableDark();

                setOpaque(false);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Tasks");

                buttonEffect1.setForeground(new java.awt.Color(255, 255, 255));
                buttonEffect1.setText("Add Task");
                buttonEffect1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                buttonEffect1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonEffect1ActionPerformed(evt);
                        }
                });

                buttonEffect2.setForeground(new java.awt.Color(255, 255, 255));
                buttonEffect2.setText("Remove Task");
                buttonEffect2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

                tableDark1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "Task Name", "Description", "Start Date", "End Date", "Priority",
                                                "Status", "Estimated Hours", "Assigned To"
                                }));
                jScrollPane2.setViewportView(tableDark1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(buttonEffect1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                87,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(buttonEffect2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                885, Short.MAX_VALUE))
                                                                .addGap(20, 20, 20)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel1)
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(buttonEffect1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(buttonEffect2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane2)
                                                                .addGap(20, 20, 20)));
        }// </editor-fold>

        private void buttonEffect1ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                taskFrame.setVisible(true);
                taskFrame.setUser(this.user);
                taskFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

        // Variables declaration - do not modify
        private ButtonEffect buttonEffect1;
        private ButtonEffect buttonEffect2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane2;
        private TableDark tableDark1;
        // End of variables declaration
}
